### ISSUE TITLE
Link to existing release docs, instead of duplicating? [DRY]

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/files.opentreeoflife.org#1]
This is in regard to the [OT Taxonomy page](http://files.opentreeoflife.org/ott/), which shows an HTML rendering of the [latest release page](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/ott2.9.md) in the reference-taxonomy docs/ folder.

Now that we show this document (as HTML) [in the main web app](https://devtree.opentreeoflife.org/about/taxonomy-version), the files homepage could probably just link there instead. In fact, it could link to the docs for all previous versions (e.g., [ott2.6](https://devtree.opentreeoflife.org/about/taxonomy-version/ott2.6)).

_Note that these release notes current appear on **devtree**, but not in production._

UPDATE: I would assign this to @jar398 , but there's no assignee list here. Odd.

**Comment by jar398** [comment]
So you are suggesting a 302 redirect from http://files.opentreeoflife.org/ott/ to https://tree.opentreeoflife.org/about/taxonomy-version ?  (I assume you mean tree. , not devtree.)
But there is content on the current page that is not present in the release notes, specifically links to experimental and to very old versions.  It's also nice, I think, to see a single list of all versions in one place.

You say "it could link to the docs for all previous versions" but that doesn't seem appropriate in the release notes for a particular version.  I would think the collection of all versions would want its own page. Also, doing a 307 redirect (that's what it is, right?) from a generic-sounding URL (about/taxonomy-version) to a release-specific page thwarts bookmarking.

I'm also uncomfortable with the level of involvement of Javascript (the prev/next widget and dropdown) in getting access to these files. I would much prefer proper hyperlinks.

**Comment by jimallman** [comment]
> But there is content on the current page that is not present in the release notes, specifically links to experimental and to very old versions. It's also nice, I think, to see a single list of all versions in one place.

Good point about the experimental versions, which aren't listed in the webapp. (Should they be?)

> Also, doing a 307 redirect (that's what it is, right?) from a generic-sounding URL (about/taxonomy-version) to a release-specific page thwarts bookmarking.

It's a 303 (See Other) redirect, actually. My rationale for this behavior is that `/about/taxonomy-version` means "Show me the [latest] taxonomy version", which then redirects to `/about/taxonomy-version/ott2.8` or whatever is the latest. Both URLs are worth bookmarking, but for different reasons.

> I'm also uncomfortable with the level of involvement of Javascript (the prev/next widget and dropdown) in getting access to these files. I would much prefer proper hyperlinks.

We **could** degrade gracefully here, with the "raw" HTML displaying a header box that lists all versions using traditional hyperlinks. Our JS would then scan this and warp it into the current UI, basically turning a list of links into a SELECT widget.

**Comment by jar398** [comment]
I did a little work on the ott/ index page. It now links back to the web application, as well as to github. Since I want to keep this as a static (non-JS) page, and to preserve the ability to add things to it (like experimental versions) without redeploying the webapp, I think this is all I want to do on this issue. If I hear no objections I'll close this issue.
